In [68]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [69]:
df1 = pd.read_csv("10_duttonrage.csv")
df1.tail()

,Unnamed: 0,Make,Model,Price,Year,Listing Type,Transmission
49,49,Mercedes-Benz,280SL Pagoda,NaN,1970.0,NaN,NaN
50,50,NaN,Jaguar E-Type 4.2 F H Coupe,NaN,1964.0,NaN,NaN
51,51,Porsche,356SC Coupe 2dr Man 4sp 1600,35999000.0,1964.0,NaN,NaN
52,52,Lamborghini,Miura P400 S,NaN,1969.0,NaN,NaN
53,53,Porsche,959,219999000.0,1987.0,NaN,NaN

In [70]:
df1=df1.drop("Unnamed: 0",axis=1)

In [73]:
df1.head()

,Make,Model,Price,Year,Listing Type,Transmission
0,Porsche,911 992 Carrera S Coupe 2dr PDK 8sp 3.0TT [MY21],NaN,2020.0,NaN,NaN
1,BMW,i8 I12 LCI Coupe 2dr Auto 6sp AWD 1.5T/105kW ...,NaN,2019.0,NaN,NaN
2,Land Rover,Defender 90 Adventure Wagon 3dr Man 6sp 4x4 2...,10999000.0,2015.0,NaN,NaN
3,Porsche,911 997 Series II Carrera Cabriolet 2dr PDK 7...,NaN,2009.0,NaN,NaN
4,Porsche,Cayenne 9YB Turbo Coupe 5dr Tiptronic 8sp 4x4...,NaN,2020.0,NaN,NaN

In [74]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 6 columns):
Make            51 non-null object
Model           54 non-null object
Price           39 non-null float64
Year            53 non-null float64
Listing Type    0 non-null float64
Transmission    0 non-null float64
dtypes: float64(4), object(2)
memory usage: 2.6+ KB

In [75]:
df1.describe()

              Price         Year  Listing Type  Transmission
count  3.900000e+01    53.000000           0.0           0.0
mean   3.209387e+07  2006.037736           NaN           NaN
std    3.636048e+07    18.072463           NaN           NaN
min    2.499000e+06  1960.000000           NaN           NaN
25%    1.199900e+07  2004.000000           NaN           NaN
50%    2.499900e+07  2014.000000           NaN           NaN
75%    3.674900e+07  2019.000000           NaN           NaN
max    2.199990e+08  2021.000000           NaN           NaN

## Manufacturer

In [76]:
#Number of unique manufacturers

unique_manufacturer = df1["Make"].nunique()
print("Number of unique manufacturer :",unique_manufacturer )

Number of unique manufacturer : 13

In [77]:
#Names of unique manufacturers

df1["Make"].unique()

array(['Porsche', 'BMW', 'Land Rover', 'Mercedes-Benz', 'Maserati',
       'Ferrari', 'Lexus', 'Tesla', 'Lamborghini', 'HARLEY DAVIDSON',
       'McLaren', 'Mazda', 'Bentley', nan], dtype=object)

In [78]:
#Percentages of different manufacturer's cars

percentage = df1['Make'].value_counts(normalize=True).mul(100).round(1).astype(str) + '%'
print("Percentage of different cars\n",percentage)

Percentage of different cars
 Ferrari            23.5%
Porsche            21.6%
Mercedes-Benz      15.7%
BMW                 9.8%
McLaren             7.8%
Land Rover          3.9%
Lamborghini         3.9%
Maserati            3.9%
HARLEY DAVIDSON     2.0%
Tesla               2.0%
Lexus               2.0%
Bentley             2.0%
Mazda               2.0%
Name: Make, dtype: object

## Year

In [79]:
#Number of different year's cars

year_count = df1['Year'].value_counts()
print("Number of cars in different years\n",year_count)

Number of cars in different years
 2019.0    10
2017.0     5
2020.0     3
2018.0     3
2015.0     3
1964.0     3
2004.0     3
2014.0     3
1987.0     2
2009.0     2
2005.0     2
2006.0     2
2008.0     2
2012.0     2
1969.0     1
2016.0     1
1970.0     1
1967.0     1
1986.0     1
1997.0     1
1960.0     1
2021.0     1
Name: Year, dtype: int64

In [80]:
#Percentage of differet year's cars

percentage = df1['Year'].value_counts(normalize=True).mul(100).round(1).astype(str) + '%'
print("Percentage of cars in different years\n",percentage)

Percentage of cars in different years
 2019.0    18.9%
2017.0     9.4%
2020.0     5.7%
2018.0     5.7%
2015.0     5.7%
1964.0     5.7%
2004.0     5.7%
2014.0     5.7%
1987.0     3.8%
2009.0     3.8%
2005.0     3.8%
2006.0     3.8%
2008.0     3.8%
2012.0     3.8%
1969.0     1.9%
2016.0     1.9%
1970.0     1.9%
1967.0     1.9%
1986.0     1.9%
1997.0     1.9%
1960.0     1.9%
2021.0     1.9%
Name: Year, dtype: object

In [81]:
oldest = df1["Year"].min()
print("Oldest car year:",int(oldest))

Oldest car year: 1960

In [82]:
latest = df1["Year"].max()
print("Latest car year:",int(latest))

Latest car year: 2021

In [83]:
#Number of null values in each column

df1.isnull().sum()

Make             3
Model            0
Price           15
Year             1
Listing Type    54
Transmission    54
dtype: int64

## Price

In [84]:
#sorting prices of cars in ascending order

df1 = df1.sort_values("Price")
df1

,Make,Model,Price,Year,Listing Type,Transmission
22,HARLEY DAVIDSON,FLHTCU ULTRA CLASSIC,2499000.0,2012.0,NaN,NaN
24,Mazda,RX-8 FE Series 2 Luxury Coupe 4dr Spts Auto 6...,4999000.0,2008.0,NaN,NaN
15,Tesla,Model S 85 Sportback 5dr Reduction Gear 1sp A...,6999000.0,2014.0,NaN,NaN
16,Mercedes-Benz,C-Class W205 C63 AMG S Sedan 4dr SPEEDSHIFT M...,10499000.0,2017.0,NaN,NaN
2,Land Rover,Defender 90 Adventure Wagon 3dr Man 6sp 4x4 2...,10999000.0,2015.0,NaN,NaN
6,Maserati,Levante M161 Luxury Wagon 5dr Spts Auto 8sp Q...,10999000.0,2017.0,NaN,NaN
42,NaN,Austin Healey 3000 Mk III Convertible 2dr Man ...,10999000.0,1967.0,NaN,NaN
13,BMW,X5 G05 xDrive30d M Sport Wagon 5dr Steptronic...,10999000.0,2019.0,NaN,NaN
19,Porsche,Macan 95B GTS Wagon 5dr PDK 7sp AWD 3.0TT [MY18],10999000.0,2017.0,NaN,NaN
7,BMW,M4 F82 LCI Competition Coupe 2dr M-DCT 7sp 3.0TT,11999000.0,2019.0,NaN,NaN
14,BMW,7 Series G12 750Li Sedan 4dr Steptronic 8sp 4...,11999000.0,2016.0,NaN,NaN
9,Porsche,Cayenne 9YA Wagon 5dr Tiptronic 8sp 4x4 3.0T ...,13999000.0,2019.0,NaN,NaN
11,Mercedes-Benz,GLC-Class X253 GLC63 AMG S Wagon 5dr SPEEDSHI...,14499000.0,2019.0,NaN,NaN
20,Mercedes-Benz,C-Class W205 C63 AMG S Sedan 4dr SPEEDSHIFT M...,15999000.0,2019.0,NaN,NaN
21,BMW,i8 I12 Coupe 2dr Auto 6sp AWD 1.5T/96kW Hybri...,17999000.0,2014.0,NaN,NaN
33,Land Rover,Range Rover L405 SDV8 Vogue SE Wagon 5dr Spts...,18999000.0,2018.0,NaN,NaN
27,Ferrari,612 Scaglietti F137 Coupe 2dr Seq. Mac 6sp 5.7i,19999000.0,2006.0,NaN,NaN
8,Ferrari,348 sp Convertible 2dr Man 5sp 3.4i,21999000.0,2004.0,NaN,NaN
46,Ferrari,328 GTS Coupe 2dr Man 5sp 3.2i,22999000.0,1987.0,NaN,NaN
17,Lamborghini,Gallardo L140 LP550-2 Coupe 2dr E-Gear 6sp 5.2i,24999000.0,2012.0,NaN,NaN
18,Mercedes-Benz,S-Class W223 S450 Sedan 4dr 9G-TRONIC 9sp 4MA...,26999000.0,2021.0,NaN,NaN
30,Ferrari,599 Fiorano GTB Coupe 2dr Seq. Mac 6sp 6.0i [...,26999000.0,2006.0,NaN,NaN
35,Porsche,911 996 GT2 Coupe 2dr Man 6sp 3.6TT [MY03],26999000.0,2004.0,NaN,NaN
41,McLaren,650S Spider 2dr SSG 7sp 3.8TT [MY15],27999000.0,2014.0,NaN,NaN
47,Ferrari,F355 Spider Convertible 2dr Man 6sp 3.5i,29999000.0,1997.0,NaN,NaN
34,Porsche,Panamera 971 Turbo S E-Hybrid Sedan 4dr PDK 8...,29999000.0,2017.0,NaN,NaN
25,Mercedes-Benz,G-Class W463 G63 AMG Wagon 5dr SPEEDSHIFT 9sp...,30999000.0,2018.0,NaN,NaN
48,Mercedes-Benz,190SL R121 Roadster 2dr Man 4sp 1.9,31999000.0,1960.0,NaN,NaN
51,Porsche,356SC Coupe 2dr Man 4sp 1600,35999000.0,1964.0,NaN,NaN
26,Ferrari,612 Scaglietti F137 Coupe 2dr Seq. Mac 6sp 5.7i,37499000.0,2009.0,NaN,NaN
29,McLaren,GT MA3 Coupe 2dr SSG 7sp 4.0TT [MY20],39999000.0,2020.0,NaN,NaN
28,Bentley,Continental 3S GT Coupe 2dr DCT 8sp 4x4 6.0TT...,41999000.0,2019.0,NaN,NaN
23,McLaren,600LT P13 Coupe 2dr SSG 7sp 3.8TT [MY19],46599000.0,2019.0,NaN,NaN
44,Ferrari,Testarossa Monospecchio,47999000.0,1986.0,NaN,NaN
37,McLaren,675LT Coupe 2dr SSG 7sp 3.8TT [Jul],49999000.0,2015.0,NaN,NaN
36,Ferrari,F430 F136 Scuderia Coupe 2dr Seq. Mac 6sp 4.3i,54999000.0,2008.0,NaN,NaN
32,Ferrari,458 Speciale F142 Coupe 2dr DCT 7sp 4.5i,69999000.0,2015.0,NaN,NaN
31,Ferrari,488 Pista Spider F142 Convertible 2dr DCT 7sp...,99099000.0,2019.0,NaN,NaN
53,Porsche,959,219999000.0,1987.0,NaN,NaN
0,Porsche,911 992 Carrera S Coupe 2dr PDK 8sp 3.0TT [MY21],NaN,2020.0,NaN,NaN
1,BMW,i8 I12 LCI Coupe 2dr Auto 6sp AWD 1.5T/105kW ...,NaN,2019.0,NaN,NaN
3,Porsche,911 997 Series II Carrera Cabriolet 2dr PDK 7...,NaN,2009.0,NaN,NaN
4,Porsche,Cayenne 9YB Turbo Coupe 5dr Tiptronic 8sp 4x4...,NaN,2020.0,NaN,NaN
5,Mercedes-Benz,C-Class C205 C63 AMG S Coupe 2dr SPEEDSHIFT M...,NaN,2019.0,NaN,NaN
10,Porsche,Cayenne 9YA Turbo Wagon 5dr Tiptronic 8sp 4x4...,NaN,2018.0,NaN,NaN
12,Lexus,"LC URZ100R LC500 Coupe 2dr Spts Auto 10sp, 5....",NaN,2017.0,NaN,NaN
38,Porsche,Carrera GT,NaN,2005.0,NaN,NaN
39,Ferrari,Enzo,NaN,2004.0,NaN,NaN
40,Maserati,MC12,NaN,2005.0,NaN,NaN
43,Ferrari,330 GT 2+2 Coupe 2dr Man 5sp 4.0,NaN,1964.0,NaN,NaN
45,NaN,Cooper BRM F2,NaN,NaN,NaN,NaN
49,Mercedes-Benz,280SL Pagoda,NaN,1970.0,NaN,NaN
50,NaN,Jaguar E-Type 4.2 F H Coupe,NaN,1964.0,NaN,NaN
52,Lamborghini,Miura P400 S,NaN,1969.0,NaN,NaN

In [85]:
#Lowest car amount

lowest_price_range = df1["Price"].min()
print("Lowest price range: $",lowest_price_range)

Lowest price range: $ 2499000.0

In [86]:
#Highest car amount

highest_price_range = df1["Price"].max()
print("Highest price range: $",highest_price_range)

Highest price range: $ 219999000.0

### Average price of each maufacturer

In [87]:
df1["Average"]=df1.groupby(["Make"]).Price.transform('mean')
df1

,Make,Model,Price,Year,Listing Type,Transmission,Average
22,HARLEY DAVIDSON,FLHTCU ULTRA CLASSIC,2499000.0,2012.0,NaN,NaN,2.499000e+06
24,Mazda,RX-8 FE Series 2 Luxury Coupe 4dr Spts Auto 6...,4999000.0,2008.0,NaN,NaN,4.999000e+06
15,Tesla,Model S 85 Sportback 5dr Reduction Gear 1sp A...,6999000.0,2014.0,NaN,NaN,6.999000e+06
16,Mercedes-Benz,C-Class W205 C63 AMG S Sedan 4dr SPEEDSHIFT M...,10499000.0,2017.0,NaN,NaN,2.183233e+07
2,Land Rover,Defender 90 Adventure Wagon 3dr Man 6sp 4x4 2...,10999000.0,2015.0,NaN,NaN,1.499900e+07
6,Maserati,Levante M161 Luxury Wagon 5dr Spts Auto 8sp Q...,10999000.0,2017.0,NaN,NaN,1.099900e+07
42,NaN,Austin Healey 3000 Mk III Convertible 2dr Man ...,10999000.0,1967.0,NaN,NaN,NaN
13,BMW,X5 G05 xDrive30d M Sport Wagon 5dr Steptronic...,10999000.0,2019.0,NaN,NaN,1.324900e+07
19,Porsche,Macan 95B GTS Wagon 5dr PDK 7sp AWD 3.0TT [MY18],10999000.0,2017.0,NaN,NaN,5.633233e+07
7,BMW,M4 F82 LCI Competition Coupe 2dr M-DCT 7sp 3.0TT,11999000.0,2019.0,NaN,NaN,1.324900e+07
14,BMW,7 Series G12 750Li Sedan 4dr Steptronic 8sp 4...,11999000.0,2016.0,NaN,NaN,1.324900e+07
9,Porsche,Cayenne 9YA Wagon 5dr Tiptronic 8sp 4x4 3.0T ...,13999000.0,2019.0,NaN,NaN,5.633233e+07
11,Mercedes-Benz,GLC-Class X253 GLC63 AMG S Wagon 5dr SPEEDSHI...,14499000.0,2019.0,NaN,NaN,2.183233e+07
20,Mercedes-Benz,C-Class W205 C63 AMG S Sedan 4dr SPEEDSHIFT M...,15999000.0,2019.0,NaN,NaN,2.183233e+07
21,BMW,i8 I12 Coupe 2dr Auto 6sp AWD 1.5T/96kW Hybri...,17999000.0,2014.0,NaN,NaN,1.324900e+07
33,Land Rover,Range Rover L405 SDV8 Vogue SE Wagon 5dr Spts...,18999000.0,2018.0,NaN,NaN,1.499900e+07
27,Ferrari,612 Scaglietti F137 Coupe 2dr Seq. Mac 6sp 5.7i,19999000.0,2006.0,NaN,NaN,4.315900e+07
8,Ferrari,348 sp Convertible 2dr Man 5sp 3.4i,21999000.0,2004.0,NaN,NaN,4.315900e+07
46,Ferrari,328 GTS Coupe 2dr Man 5sp 3.2i,22999000.0,1987.0,NaN,NaN,4.315900e+07
17,Lamborghini,Gallardo L140 LP550-2 Coupe 2dr E-Gear 6sp 5.2i,24999000.0,2012.0,NaN,NaN,2.499900e+07
18,Mercedes-Benz,S-Class W223 S450 Sedan 4dr 9G-TRONIC 9sp 4MA...,26999000.0,2021.0,NaN,NaN,2.183233e+07
30,Ferrari,599 Fiorano GTB Coupe 2dr Seq. Mac 6sp 6.0i [...,26999000.0,2006.0,NaN,NaN,4.315900e+07
35,Porsche,911 996 GT2 Coupe 2dr Man 6sp 3.6TT [MY03],26999000.0,2004.0,NaN,NaN,5.633233e+07
41,McLaren,650S Spider 2dr SSG 7sp 3.8TT [MY15],27999000.0,2014.0,NaN,NaN,4.114900e+07
47,Ferrari,F355 Spider Convertible 2dr Man 6sp 3.5i,29999000.0,1997.0,NaN,NaN,4.315900e+07
34,Porsche,Panamera 971 Turbo S E-Hybrid Sedan 4dr PDK 8...,29999000.0,2017.0,NaN,NaN,5.633233e+07
25,Mercedes-Benz,G-Class W463 G63 AMG Wagon 5dr SPEEDSHIFT 9sp...,30999000.0,2018.0,NaN,NaN,2.183233e+07
48,Mercedes-Benz,190SL R121 Roadster 2dr Man 4sp 1.9,31999000.0,1960.0,NaN,NaN,2.183233e+07
51,Porsche,356SC Coupe 2dr Man 4sp 1600,35999000.0,1964.0,NaN,NaN,5.633233e+07
26,Ferrari,612 Scaglietti F137 Coupe 2dr Seq. Mac 6sp 5.7i,37499000.0,2009.0,NaN,NaN,4.315900e+07
29,McLaren,GT MA3 Coupe 2dr SSG 7sp 4.0TT [MY20],39999000.0,2020.0,NaN,NaN,4.114900e+07
28,Bentley,Continental 3S GT Coupe 2dr DCT 8sp 4x4 6.0TT...,41999000.0,2019.0,NaN,NaN,4.199900e+07
23,McLaren,600LT P13 Coupe 2dr SSG 7sp 3.8TT [MY19],46599000.0,2019.0,NaN,NaN,4.114900e+07
44,Ferrari,Testarossa Monospecchio,47999000.0,1986.0,NaN,NaN,4.315900e+07
37,McLaren,675LT Coupe 2dr SSG 7sp 3.8TT [Jul],49999000.0,2015.0,NaN,NaN,4.114900e+07
36,Ferrari,F430 F136 Scuderia Coupe 2dr Seq. Mac 6sp 4.3i,54999000.0,2008.0,NaN,NaN,4.315900e+07
32,Ferrari,458 Speciale F142 Coupe 2dr DCT 7sp 4.5i,69999000.0,2015.0,NaN,NaN,4.315900e+07
31,Ferrari,488 Pista Spider F142 Convertible 2dr DCT 7sp...,99099000.0,2019.0,NaN,NaN,4.315900e+07
53,Porsche,959,219999000.0,1987.0,NaN,NaN,5.633233e+07
0,Porsche,911 992 Carrera S Coupe 2dr PDK 8sp 3.0TT [MY21],NaN,2020.0,NaN,NaN,5.633233e+07
1,BMW,i8 I12 LCI Coupe 2dr Auto 6sp AWD 1.5T/105kW ...,NaN,2019.0,NaN,NaN,1.324900e+07
3,Porsche,911 997 Series II Carrera Cabriolet 2dr PDK 7...,NaN,2009.0,NaN,NaN,5.633233e+07
4,Porsche,Cayenne 9YB Turbo Coupe 5dr Tiptronic 8sp 4x4...,NaN,2020.0,NaN,NaN,5.633233e+07
5,Mercedes-Benz,C-Class C205 C63 AMG S Coupe 2dr SPEEDSHIFT M...,NaN,2019.0,NaN,NaN,2.183233e+07
10,Porsche,Cayenne 9YA Turbo Wagon 5dr Tiptronic 8sp 4x4...,NaN,2018.0,NaN,NaN,5.633233e+07
12,Lexus,"LC URZ100R LC500 Coupe 2dr Spts Auto 10sp, 5....",NaN,2017.0,NaN,NaN,NaN
38,Porsche,Carrera GT,NaN,2005.0,NaN,NaN,5.633233e+07
39,Ferrari,Enzo,NaN,2004.0,NaN,NaN,4.315900e+07
40,Maserati,MC12,NaN,2005.0,NaN,NaN,1.099900e+07
43,Ferrari,330 GT 2+2 Coupe 2dr Man 5sp 4.0,NaN,1964.0,NaN,NaN,4.315900e+07
45,NaN,Cooper BRM F2,NaN,NaN,NaN,NaN,NaN
49,Mercedes-Benz,280SL Pagoda,NaN,1970.0,NaN,NaN,2.183233e+07
50,NaN,Jaguar E-Type 4.2 F H Coupe,NaN,1964.0,NaN,NaN,NaN
52,Lamborghini,Miura P400 S,NaN,1969.0,NaN,NaN,2.499900e+07

### Percentile rank

In [88]:
df1['Percentile Rank'] = df1.Price.rank(pct = True)
df1

,Make,Model,Price,Year,Listing Type,Transmission,Average,Percentile Rank
22,HARLEY DAVIDSON,FLHTCU ULTRA CLASSIC,2499000.0,2012.0,NaN,NaN,2.499000e+06,0.025641
24,Mazda,RX-8 FE Series 2 Luxury Coupe 4dr Spts Auto 6...,4999000.0,2008.0,NaN,NaN,4.999000e+06,0.051282
15,Tesla,Model S 85 Sportback 5dr Reduction Gear 1sp A...,6999000.0,2014.0,NaN,NaN,6.999000e+06,0.076923
16,Mercedes-Benz,C-Class W205 C63 AMG S Sedan 4dr SPEEDSHIFT M...,10499000.0,2017.0,NaN,NaN,2.183233e+07,0.102564
2,Land Rover,Defender 90 Adventure Wagon 3dr Man 6sp 4x4 2...,10999000.0,2015.0,NaN,NaN,1.499900e+07,0.179487
6,Maserati,Levante M161 Luxury Wagon 5dr Spts Auto 8sp Q...,10999000.0,2017.0,NaN,NaN,1.099900e+07,0.179487
42,NaN,Austin Healey 3000 Mk III Convertible 2dr Man ...,10999000.0,1967.0,NaN,NaN,NaN,0.179487
13,BMW,X5 G05 xDrive30d M Sport Wagon 5dr Steptronic...,10999000.0,2019.0,NaN,NaN,1.324900e+07,0.179487
19,Porsche,Macan 95B GTS Wagon 5dr PDK 7sp AWD 3.0TT [MY18],10999000.0,2017.0,NaN,NaN,5.633233e+07,0.179487
7,BMW,M4 F82 LCI Competition Coupe 2dr M-DCT 7sp 3.0TT,11999000.0,2019.0,NaN,NaN,1.324900e+07,0.269231
14,BMW,7 Series G12 750Li Sedan 4dr Steptronic 8sp 4...,11999000.0,2016.0,NaN,NaN,1.324900e+07,0.269231
9,Porsche,Cayenne 9YA Wagon 5dr Tiptronic 8sp 4x4 3.0T ...,13999000.0,2019.0,NaN,NaN,5.633233e+07,0.307692
11,Mercedes-Benz,GLC-Class X253 GLC63 AMG S Wagon 5dr SPEEDSHI...,14499000.0,2019.0,NaN,NaN,2.183233e+07,0.333333
20,Mercedes-Benz,C-Class W205 C63 AMG S Sedan 4dr SPEEDSHIFT M...,15999000.0,2019.0,NaN,NaN,2.183233e+07,0.358974
21,BMW,i8 I12 Coupe 2dr Auto 6sp AWD 1.5T/96kW Hybri...,17999000.0,2014.0,NaN,NaN,1.324900e+07,0.384615
33,Land Rover,Range Rover L405 SDV8 Vogue SE Wagon 5dr Spts...,18999000.0,2018.0,NaN,NaN,1.499900e+07,0.410256
27,Ferrari,612 Scaglietti F137 Coupe 2dr Seq. Mac 6sp 5.7i,19999000.0,2006.0,NaN,NaN,4.315900e+07,0.435897
8,Ferrari,348 sp Convertible 2dr Man 5sp 3.4i,21999000.0,2004.0,NaN,NaN,4.315900e+07,0.461538
46,Ferrari,328 GTS Coupe 2dr Man 5sp 3.2i,22999000.0,1987.0,NaN,NaN,4.315900e+07,0.487179
17,Lamborghini,Gallardo L140 LP550-2 Coupe 2dr E-Gear 6sp 5.2i,24999000.0,2012.0,NaN,NaN,2.499900e+07,0.512821
18,Mercedes-Benz,S-Class W223 S450 Sedan 4dr 9G-TRONIC 9sp 4MA...,26999000.0,2021.0,NaN,NaN,2.183233e+07,0.564103
30,Ferrari,599 Fiorano GTB Coupe 2dr Seq. Mac 6sp 6.0i [...,26999000.0,2006.0,NaN,NaN,4.315900e+07,0.564103
35,Porsche,911 996 GT2 Coupe 2dr Man 6sp 3.6TT [MY03],26999000.0,2004.0,NaN,NaN,5.633233e+07,0.564103
41,McLaren,650S Spider 2dr SSG 7sp 3.8TT [MY15],27999000.0,2014.0,NaN,NaN,4.114900e+07,0.615385
47,Ferrari,F355 Spider Convertible 2dr Man 6sp 3.5i,29999000.0,1997.0,NaN,NaN,4.315900e+07,0.653846
34,Porsche,Panamera 971 Turbo S E-Hybrid Sedan 4dr PDK 8...,29999000.0,2017.0,NaN,NaN,5.633233e+07,0.653846
25,Mercedes-Benz,G-Class W463 G63 AMG Wagon 5dr SPEEDSHIFT 9sp...,30999000.0,2018.0,NaN,NaN,2.183233e+07,0.692308
48,Mercedes-Benz,190SL R121 Roadster 2dr Man 4sp 1.9,31999000.0,1960.0,NaN,NaN,2.183233e+07,0.717949
51,Porsche,356SC Coupe 2dr Man 4sp 1600,35999000.0,1964.0,NaN,NaN,5.633233e+07,0.743590
26,Ferrari,612 Scaglietti F137 Coupe 2dr Seq. Mac 6sp 5.7i,37499000.0,2009.0,NaN,NaN,4.315900e+07,0.769231
29,McLaren,GT MA3 Coupe 2dr SSG 7sp 4.0TT [MY20],39999000.0,2020.0,NaN,NaN,4.114900e+07,0.794872
28,Bentley,Continental 3S GT Coupe 2dr DCT 8sp 4x4 6.0TT...,41999000.0,2019.0,NaN,NaN,4.199900e+07,0.820513
23,McLaren,600LT P13 Coupe 2dr SSG 7sp 3.8TT [MY19],46599000.0,2019.0,NaN,NaN,4.114900e+07,0.846154
44,Ferrari,Testarossa Monospecchio,47999000.0,1986.0,NaN,NaN,4.315900e+07,0.871795
37,McLaren,675LT Coupe 2dr SSG 7sp 3.8TT [Jul],49999000.0,2015.0,NaN,NaN,4.114900e+07,0.897436
36,Ferrari,F430 F136 Scuderia Coupe 2dr Seq. Mac 6sp 4.3i,54999000.0,2008.0,NaN,NaN,4.315900e+07,0.923077
32,Ferrari,458 Speciale F142 Coupe 2dr DCT 7sp 4.5i,69999000.0,2015.0,NaN,NaN,4.315900e+07,0.948718
31,Ferrari,488 Pista Spider F142 Convertible 2dr DCT 7sp...,99099000.0,2019.0,NaN,NaN,4.315900e+07,0.974359
53,Porsche,959,219999000.0,1987.0,NaN,NaN,5.633233e+07,1.000000
0,Porsche,911 992 Carrera S Coupe 2dr PDK 8sp 3.0TT [MY21],NaN,2020.0,NaN,NaN,5.633233e+07,NaN
1,BMW,i8 I12 LCI Coupe 2dr Auto 6sp AWD 1.5T/105kW ...,NaN,2019.0,NaN,NaN,1.324900e+07,NaN
3,Porsche,911 997 Series II Carrera Cabriolet 2dr PDK 7...,NaN,2009.0,NaN,NaN,5.633233e+07,NaN
4,Porsche,Cayenne 9YB Turbo Coupe 5dr Tiptronic 8sp 4x4...,NaN,2020.0,NaN,NaN,5.633233e+07,NaN
5,Mercedes-Benz,C-Class C205 C63 AMG S Coupe 2dr SPEEDSHIFT M...,NaN,2019.0,NaN,NaN,2.183233e+07,NaN
10,Porsche,Cayenne 9YA Turbo Wagon 5dr Tiptronic 8sp 4x4...,NaN,2018.0,NaN,NaN,5.633233e+07,NaN
12,Lexus,"LC URZ100R LC500 Coupe 2dr Spts Auto 10sp, 5....",NaN,2017.0,NaN,NaN,NaN,NaN
38,Porsche,Carrera GT,NaN,2005.0,NaN,NaN,5.633233e+07,NaN
39,Ferrari,Enzo,NaN,2004.0,NaN,NaN,4.315900e+07,NaN
40,Maserati,MC12,NaN,2005.0,NaN,NaN,1.099900e+07,NaN
43,Ferrari,330 GT 2+2 Coupe 2dr Man 5sp 4.0,NaN,1964.0,NaN,NaN,4.315900e+07,NaN
45,NaN,Cooper BRM F2,NaN,NaN,NaN,NaN,NaN,NaN
49,Mercedes-Benz,280SL Pagoda,NaN,1970.0,NaN,NaN,2.183233e+07,NaN
50,NaN,Jaguar E-Type 4.2 F H Coupe,NaN,1964.0,NaN,NaN,NaN,NaN
52,Lamborghini,Miura P400 S,NaN,1969.0,NaN,NaN,2.499900e+07,NaN

In [89]:
#sorting prices of cars in ascending order

df1 = df1.sort_values("Percentile Rank",ascending=False)
df1

,Make,Model,Price,Year,Listing Type,Transmission,Average,Percentile Rank
53,Porsche,959,219999000.0,1987.0,NaN,NaN,5.633233e+07,1.000000
31,Ferrari,488 Pista Spider F142 Convertible 2dr DCT 7sp...,99099000.0,2019.0,NaN,NaN,4.315900e+07,0.974359
32,Ferrari,458 Speciale F142 Coupe 2dr DCT 7sp 4.5i,69999000.0,2015.0,NaN,NaN,4.315900e+07,0.948718
36,Ferrari,F430 F136 Scuderia Coupe 2dr Seq. Mac 6sp 4.3i,54999000.0,2008.0,NaN,NaN,4.315900e+07,0.923077
37,McLaren,675LT Coupe 2dr SSG 7sp 3.8TT [Jul],49999000.0,2015.0,NaN,NaN,4.114900e+07,0.897436
44,Ferrari,Testarossa Monospecchio,47999000.0,1986.0,NaN,NaN,4.315900e+07,0.871795
23,McLaren,600LT P13 Coupe 2dr SSG 7sp 3.8TT [MY19],46599000.0,2019.0,NaN,NaN,4.114900e+07,0.846154
28,Bentley,Continental 3S GT Coupe 2dr DCT 8sp 4x4 6.0TT...,41999000.0,2019.0,NaN,NaN,4.199900e+07,0.820513
29,McLaren,GT MA3 Coupe 2dr SSG 7sp 4.0TT [MY20],39999000.0,2020.0,NaN,NaN,4.114900e+07,0.794872
26,Ferrari,612 Scaglietti F137 Coupe 2dr Seq. Mac 6sp 5.7i,37499000.0,2009.0,NaN,NaN,4.315900e+07,0.769231
51,Porsche,356SC Coupe 2dr Man 4sp 1600,35999000.0,1964.0,NaN,NaN,5.633233e+07,0.743590
48,Mercedes-Benz,190SL R121 Roadster 2dr Man 4sp 1.9,31999000.0,1960.0,NaN,NaN,2.183233e+07,0.717949
25,Mercedes-Benz,G-Class W463 G63 AMG Wagon 5dr SPEEDSHIFT 9sp...,30999000.0,2018.0,NaN,NaN,2.183233e+07,0.692308
34,Porsche,Panamera 971 Turbo S E-Hybrid Sedan 4dr PDK 8...,29999000.0,2017.0,NaN,NaN,5.633233e+07,0.653846
47,Ferrari,F355 Spider Convertible 2dr Man 6sp 3.5i,29999000.0,1997.0,NaN,NaN,4.315900e+07,0.653846
41,McLaren,650S Spider 2dr SSG 7sp 3.8TT [MY15],27999000.0,2014.0,NaN,NaN,4.114900e+07,0.615385
18,Mercedes-Benz,S-Class W223 S450 Sedan 4dr 9G-TRONIC 9sp 4MA...,26999000.0,2021.0,NaN,NaN,2.183233e+07,0.564103
35,Porsche,911 996 GT2 Coupe 2dr Man 6sp 3.6TT [MY03],26999000.0,2004.0,NaN,NaN,5.633233e+07,0.564103
30,Ferrari,599 Fiorano GTB Coupe 2dr Seq. Mac 6sp 6.0i [...,26999000.0,2006.0,NaN,NaN,4.315900e+07,0.564103
17,Lamborghini,Gallardo L140 LP550-2 Coupe 2dr E-Gear 6sp 5.2i,24999000.0,2012.0,NaN,NaN,2.499900e+07,0.512821
46,Ferrari,328 GTS Coupe 2dr Man 5sp 3.2i,22999000.0,1987.0,NaN,NaN,4.315900e+07,0.487179
8,Ferrari,348 sp Convertible 2dr Man 5sp 3.4i,21999000.0,2004.0,NaN,NaN,4.315900e+07,0.461538
27,Ferrari,612 Scaglietti F137 Coupe 2dr Seq. Mac 6sp 5.7i,19999000.0,2006.0,NaN,NaN,4.315900e+07,0.435897
33,Land Rover,Range Rover L405 SDV8 Vogue SE Wagon 5dr Spts...,18999000.0,2018.0,NaN,NaN,1.499900e+07,0.410256
21,BMW,i8 I12 Coupe 2dr Auto 6sp AWD 1.5T/96kW Hybri...,17999000.0,2014.0,NaN,NaN,1.324900e+07,0.384615
20,Mercedes-Benz,C-Class W205 C63 AMG S Sedan 4dr SPEEDSHIFT M...,15999000.0,2019.0,NaN,NaN,2.183233e+07,0.358974
11,Mercedes-Benz,GLC-Class X253 GLC63 AMG S Wagon 5dr SPEEDSHI...,14499000.0,2019.0,NaN,NaN,2.183233e+07,0.333333
9,Porsche,Cayenne 9YA Wagon 5dr Tiptronic 8sp 4x4 3.0T ...,13999000.0,2019.0,NaN,NaN,5.633233e+07,0.307692
7,BMW,M4 F82 LCI Competition Coupe 2dr M-DCT 7sp 3.0TT,11999000.0,2019.0,NaN,NaN,1.324900e+07,0.269231
14,BMW,7 Series G12 750Li Sedan 4dr Steptronic 8sp 4...,11999000.0,2016.0,NaN,NaN,1.324900e+07,0.269231
19,Porsche,Macan 95B GTS Wagon 5dr PDK 7sp AWD 3.0TT [MY18],10999000.0,2017.0,NaN,NaN,5.633233e+07,0.179487
13,BMW,X5 G05 xDrive30d M Sport Wagon 5dr Steptronic...,10999000.0,2019.0,NaN,NaN,1.324900e+07,0.179487
42,NaN,Austin Healey 3000 Mk III Convertible 2dr Man ...,10999000.0,1967.0,NaN,NaN,NaN,0.179487
6,Maserati,Levante M161 Luxury Wagon 5dr Spts Auto 8sp Q...,10999000.0,2017.0,NaN,NaN,1.099900e+07,0.179487
2,Land Rover,Defender 90 Adventure Wagon 3dr Man 6sp 4x4 2...,10999000.0,2015.0,NaN,NaN,1.499900e+07,0.179487
16,Mercedes-Benz,C-Class W205 C63 AMG S Sedan 4dr SPEEDSHIFT M...,10499000.0,2017.0,NaN,NaN,2.183233e+07,0.102564
15,Tesla,Model S 85 Sportback 5dr Reduction Gear 1sp A...,6999000.0,2014.0,NaN,NaN,6.999000e+06,0.076923
24,Mazda,RX-8 FE Series 2 Luxury Coupe 4dr Spts Auto 6...,4999000.0,2008.0,NaN,NaN,4.999000e+06,0.051282
22,HARLEY DAVIDSON,FLHTCU ULTRA CLASSIC,2499000.0,2012.0,NaN,NaN,2.499000e+06,0.025641
0,Porsche,911 992 Carrera S Coupe 2dr PDK 8sp 3.0TT [MY21],NaN,2020.0,NaN,NaN,5.633233e+07,NaN
1,BMW,i8 I12 LCI Coupe 2dr Auto 6sp AWD 1.5T/105kW ...,NaN,2019.0,NaN,NaN,1.324900e+07,NaN
3,Porsche,911 997 Series II Carrera Cabriolet 2dr PDK 7...,NaN,2009.0,NaN,NaN,5.633233e+07,NaN
4,Porsche,Cayenne 9YB Turbo Coupe 5dr Tiptronic 8sp 4x4...,NaN,2020.0,NaN,NaN,5.633233e+07,NaN
5,Mercedes-Benz,C-Class C205 C63 AMG S Coupe 2dr SPEEDSHIFT M...,NaN,2019.0,NaN,NaN,2.183233e+07,NaN
10,Porsche,Cayenne 9YA Turbo Wagon 5dr Tiptronic 8sp 4x4...,NaN,2018.0,NaN,NaN,5.633233e+07,NaN
12,Lexus,"LC URZ100R LC500 Coupe 2dr Spts Auto 10sp, 5....",NaN,2017.0,NaN,NaN,NaN,NaN
38,Porsche,Carrera GT,NaN,2005.0,NaN,NaN,5.633233e+07,NaN
39,Ferrari,Enzo,NaN,2004.0,NaN,NaN,4.315900e+07,NaN
40,Maserati,MC12,NaN,2005.0,NaN,NaN,1.099900e+07,NaN
43,Ferrari,330 GT 2+2 Coupe 2dr Man 5sp 4.0,NaN,1964.0,NaN,NaN,4.315900e+07,NaN
45,NaN,Cooper BRM F2,NaN,NaN,NaN,NaN,NaN,NaN
49,Mercedes-Benz,280SL Pagoda,NaN,1970.0,NaN,NaN,2.183233e+07,NaN
50,NaN,Jaguar E-Type 4.2 F H Coupe,NaN,1964.0,NaN,NaN,NaN,NaN
52,Lamborghini,Miura P400 S,NaN,1969.0,NaN,NaN,2.499900e+07,NaN